steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$smart-lawyer-assist/my-app:$SHORT_SHA', '.']

# Run tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$smart-lawyer-assist/my-app:$SHORT_SHA', 'npm', 'test']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$smart-lawyer-assist/my-app:$SHORT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  args:
    - gcloud
    - run
    - deploy
    - my-app
    - --image=gcr.io/$smart-lawyer-assist/my-app:$SHORT_SHA
    - --region=us-west1
    - --platform=managed
    - --allow-unauthenticated
  entrypoint: gcloud

images:
- 'gcr.io/$smart-lawyer-assist/my-app:$SHORT_SHA'
